---

- name: Docker image
  docker_image:
    path: /vagrant/docker
    name: helloworld
    tag: 0.0.1


- name: Docker container
  docker_container:
    name: helloworld
    image: helloworld:0.0.1
    state: started
    restart_policy: unless-stopped
    ports:
     - 80:80
