---

- hosts: all

  vars:
    a: b

  become: yes
  become_method: sudo

  pre_tasks:
    - name: Epel release
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: python-pip package
      yum:
        name: python-pip
        state: present

    - name: docker-py python package
      pip:
        name: docker-py
        state: present

  roles:
    - docker
    - docker-helloworld
